apiVersion: v1
entries:
  opa:
  - apiVersion: v1
    appVersion: 3.3.0
    created: "2022-02-04T20:48:57.275107843Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 1c4006e1809fb2a6a1885d423b3f346b924ea60508ec7c181712775b5532f9d7
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-3.3.0.tgz
    version: 3.3.0
  - apiVersion: v1
    appVersion: 3.2.2
    created: "2022-02-03T03:58:27.875362568Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 9d62e997824b6714218395457be3ccc90afffa75deaf4ac08789cff2b55a7aad
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-3.2.2.tgz
    version: 3.2.2
  - apiVersion: v1
    appVersion: 3.2.1
    created: "2022-01-28T14:08:55.362570823Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: a912b200f66ac3361b61b00a8332f23b6865627a91e66b9ecdc32ba23b970399
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-3.2.1.tgz
    version: 3.2.1
  - apiVersion: v1
    appVersion: 3.2.0
    created: "2022-01-03T21:39:03.218664518Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 18bbe93209146a898879b3b7599353f69c2f8e3c21a79925a12229c653fc2c90
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-3.2.0.tgz
    version: 3.2.0
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2021-11-09T05:23:11.907446544Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: caa1efad5c800ee44de9e9a5c91fa6ff4f5059cf83e6e784c8689b244bcdfef8
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-3.1.0.tgz
    version: 3.1.0
  - apiVersion: v1
    appVersion: 3.0.0
    created: "2021-10-27T08:25:53.888422968Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 23c0b19053bb398a7178769e482d83bb177f276e6acc5a45c5a13efb2205d088
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-3.0.0.tgz
    version: 3.0.0
  - apiVersion: v1
    appVersion: 2.0.1
    created: "2021-10-23T23:03:22.733303469Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: b6210d0e7e0cd63d68aa2ab32b892cf87f4316d8ce9b7bf6e33317a44a43f61f
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-2.0.1.tgz
    version: 2.0.1
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-09-17T10:08:02.99625054Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 6995217701489c4c20c6eaffd6e6e954b9c3b807fb5806451e6528ea5e136c63
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    appVersion: 1.30.0
    created: "2021-09-17T09:04:37.805014569Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: af2fc2b562311d5bf223721555cdff16653d7678eff01470c38327a41cd0559c
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-1.30.0.tgz
    version: 1.30.0
  - apiVersion: v1
    appVersion: 1.20.0
    created: "2021-09-17T07:59:37.505496146Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 499fdbb679b388aa6b15aca278bb809e8a6d19f494fd898577db45e9e3c16a9c
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-1.20.0.tgz
    version: 1.20.0
  - apiVersion: v1
    appVersion: 0.15.1
    created: "2021-03-29T15:29:36.296895942Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: db40ad57d0127f49e6a2e00609e03377aac5c2f5cb1bc5bc16f1ae462eee7cb9
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - https://open-policy-agent.github.io/kube-mgmt/charts/opa-1.14.6.tgz
    version: 1.14.6
  - apiVersion: v1
    appVersion: 0.15.1
    created: "2021-03-29T15:29:36.295534831Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 480b39da0fa70dc289fda9607bb9f5e39b6627967bb9bf67321abc0ee8ad9b89
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    maintainers:
    - email: torinsandall@gmail.com
      name: tsandall
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    urls:
    - https://open-policy-agent.github.io/kube-mgmt/charts/opa-1.14.0.tgz
    version: 1.14.0
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-09-17T07:54:38.681516985Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 276cd90e01a9a1190067fb85a4c179bc2d8350d94532fe1e3a34a34d2c968b27
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-1.0.0.tgz
    version: 1.0.0
generated: "2022-02-04T20:48:57.273529022Z"
