apiVersion: v1
entries:
  opa:
  - apiVersion: v1
    appVersion: 2.0.0
    created: "2021-09-17T10:08:02.99625054Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 6995217701489c4c20c6eaffd6e6e954b9c3b807fb5806451e6528ea5e136c63
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v1
    appVersion: 1.30.0
    created: "2021-09-17T09:04:37.805014569Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: af2fc2b562311d5bf223721555cdff16653d7678eff01470c38327a41cd0559c
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-1.30.0.tgz
    version: 1.30.0
  - apiVersion: v1
    appVersion: 1.20.0
    created: "2021-09-17T07:59:37.505496146Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 499fdbb679b388aa6b15aca278bb809e8a6d19f494fd898577db45e9e3c16a9c
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-1.20.0.tgz
    version: 1.20.0
  - apiVersion: v1
    appVersion: 0.15.1
    created: "2021-03-29T15:29:36.296895942Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: db40ad57d0127f49e6a2e00609e03377aac5c2f5cb1bc5bc16f1ae462eee7cb9
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - https://open-policy-agent.github.io/kube-mgmt/charts/opa-1.14.6.tgz
    version: 1.14.6
  - apiVersion: v1
    appVersion: 0.15.1
    created: "2021-03-29T15:29:36.295534831Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 480b39da0fa70dc289fda9607bb9f5e39b6627967bb9bf67321abc0ee8ad9b89
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    maintainers:
    - email: torinsandall@gmail.com
      name: tsandall
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    urls:
    - https://open-policy-agent.github.io/kube-mgmt/charts/opa-1.14.0.tgz
    version: 1.14.0
  - apiVersion: v1
    appVersion: 1.0.0
    created: "2021-09-17T07:54:38.681516985Z"
    description: Open source, general-purpose policy engine. Enforce fine-grained
      invariants over arbitrary Kubernetes resources.
    digest: 276cd90e01a9a1190067fb85a4c179bc2d8350d94532fe1e3a34a34d2c968b27
    home: https://www.openpolicyagent.org
    icon: https://raw.githubusercontent.com/open-policy-agent/opa/master/logo/logo.png
    keywords:
    - opa
    - admission control
    - policy
    name: opa
    sources:
    - https://github.com/open-policy-agent/opa
    - https://github.com/open-policy-agent/kube-mgmt
    urls:
    - opa-1.0.0.tgz
    version: 1.0.0
generated: "2021-09-17T10:08:02.994754936Z"
